//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoMarketClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExchangeViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExchangeViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoMarketClient.Resources.ExchangeViewResources", typeof(ExchangeViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Balances.
        /// </summary>
        public static string AccountBalancesCaption {
            get {
                return ResourceManager.GetString("AccountBalancesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string Column_BaseCurrency {
            get {
                return ResourceManager.GetString("Column.BaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest Bid.
        /// </summary>
        public static string Column_HighestBid {
            get {
                return ResourceManager.GetString("Column.HighestBid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hr 24 High.
        /// </summary>
        public static string Column_Hr24High {
            get {
                return ResourceManager.GetString("Column.Hr24High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hr 24 Low.
        /// </summary>
        public static string Column_Hr24Low {
            get {
                return ResourceManager.GetString("Column.Hr24Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string Column_Last {
            get {
                return ResourceManager.GetString("Column_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest Ask.
        /// </summary>
        public static string Column_LowestAsk {
            get {
                return ResourceManager.GetString("Column.LowestAsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend.
        /// </summary>
        public static string Column_Trend {
            get {
                return ResourceManager.GetString("Column_Trend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Volume.
        /// </summary>
        public static string Column_Volume {
            get {
                return ResourceManager.GetString("Column.Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} in a data-queue.
        /// </summary>
        public static string DataCountQueStatusFormatString {
            get {
                return ResourceManager.GetString("DataCountQueStatusFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Market.
        /// </summary>
        public static string EnterMarketCaption {
            get {
                return ResourceManager.GetString("EnterMarketCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order List.
        /// </summary>
        public static string OrderListCaption {
            get {
                return ResourceManager.GetString("OrderListCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Only Favorites.
        /// </summary>
        public static string ShowOnlyFavoritesCaption {
            get {
                return ResourceManager.GetString("ShowOnlyFavoritesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string StatusText_Connected {
            get {
                return ResourceManager.GetString("StatusText_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string StatusText_Connecting {
            get {
                return ResourceManager.GetString("StatusText_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Interrupted.
        /// </summary>
        public static string StatusText_ConnectionInterrupted {
            get {
                return ResourceManager.GetString("StatusText_ConnectionInterrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string StatusText_Disconnected {
            get {
                return ResourceManager.GetString("StatusText_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        public static string StatusText_Initializing {
            get {
                return ResourceManager.GetString("StatusText_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Incremental Update.
        /// </summary>
        public static string StatusText_MissingIncrementalUpdate {
            get {
                return ResourceManager.GetString("StatusText_MissingIncrementalUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data.
        /// </summary>
        public static string StatusText_NoData {
            get {
                return ResourceManager.GetString("StatusText_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        public static string StatusText_Reconnect {
            get {
                return ResourceManager.GetString("StatusText_Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Socket Error.
        /// </summary>
        public static string StatusText_SocketError {
            get {
                return ResourceManager.GetString("StatusText_SocketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting....
        /// </summary>
        public static string StatusText_Waiting {
            get {
                return ResourceManager.GetString("StatusText_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade History.
        /// </summary>
        public static string TradeHistoryCaption {
            get {
                return ResourceManager.GetString("TradeHistoryCaption", resourceCulture);
            }
        }
    }
}
